apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/genai-stack-aknot242-net: "true"
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: AWS_ACCESS_KEY_ID
            - name: AWS_DEFAULT_REGION
            - name: AWS_SECRET_ACCESS_KEY
            - name: EMBEDDING_MODEL
              value: sentence_transformer
            - name: LANGCHAIN_API_KEY
            - name: LANGCHAIN_ENDPOINT
              value: '"https://api.smith.langchain.com"'
            - name: LANGCHAIN_PROJECT
            - name: LANGCHAIN_TRACING_V2
              value: "false"
            - name: LLM
              value: "mistral:7b-instruct-v0.2-q2_K"
            - name: NEO4J_PASSWORD
              value: password
            - name: NEO4J_URI
              value: neo4j://database:7687
            - name: NEO4J_USERNAME
              value: neo4j
            - name: OLLAMA_BASE_URL
              value: http://llm:11434
            - name: OPENAI_API_KEY
          image: ghcr.io/aknot242/genai-stack-api
          name: api
          ports:
            - containerPort: 8504
              hostPort: 8504
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /embedding_model
              name: api-claim0
      restartPolicy: Always
      volumes:
        - name: api-claim0
          persistentVolumeClaim:
            claimName: api-claim0
status: {}
