apiVersion: batch/v1
kind: Job
metadata:
  labels:
    io.kompose.service: pull-model
  name: pull-model
spec:
  template:
    spec:
      containers:
        - env:
            - name: LLM
              value: "mistral:7b-instruct-q4_K_S"
            - name: OLLAMA_BASE_URL
              value: http://llm:11434
          image: ghcr.io/aknot242/genai-stack-pull-model
          name: pull-model
          resources: {}
      restartPolicy: Never
  backoffLimit: 4
