apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: pull-model
  name: pull-model
spec:
  selector:
    matchLabels:
      io.kompose.service: pull-model
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/genai-stack-aknot242-net: "true"
        io.kompose.service: pull-model
    spec:
      containers:
        - env:
            - name: LLM
              value: "mistral:instruct"
            - name: OLLAMA_BASE_URL
              value: http://llm:11434
          image: ghcr.io/aknot242/genai-stack-pull-model
          name: pull-model
          resources: {}
      restartPolicy: Never
  backoffLimit: 4
status: {}
