---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: genai-stack
spec:
  host: "*.access.udf.f5.com"
  upstreams:
    - name: bot
      service: bot
      port: 8501
    - name: loader
      service: loader
      port: 8502
    - name: pdf-bot
      service: pdf-bot
      port: 8503
    - name: api
      service: api
      port: 8504
    - name: front-end
      service: front-end
      port: 8505
  routes:
    - path: /bot
      action:
        pass: bot
    - path: /loader
      action:
        pass: loader
    - path: /pdf-bot
      action:
        pass: pdf-bot
    - path: /api
      action:
        pass: api
    - path: /front-end
      action:
        pass: front-end
